### ISSUE TITLE
Crash on refresh in home fragment

### ISSUE THREAD

**Issue by raystatic** [coding-blocks/CBOnlineApp#263]
**Describe the bug**
Crash on refresh in home fragment

**To Reproduce**
1. Go to 'Home Fragment'
2. Swipe down to refresh
3. App crashes

**Expected behavior**
It should not crash 

**Logs**
2019-06-06 01:13:05.128 22663-22663/com.codingblocks.cbonlineapp.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingblocks.cbonlineapp.debug, PID: 22663
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: CourseSection.run_id (code 1299)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:798)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:64)
        at com.codingblocks.cbonlineapp.database.CourseRunDao_Impl.insertNew(CourseRunDao_Impl.java:418)
        at com.codingblocks.cbonlineapp.database.CourseRunDao_Impl.insertNew(CourseRunDao_Impl.java:22)
        at com.codingblocks.cbonlineapp.viewmodels.HomeViewModel$fetchRecommendedCourses$1.invoke(HomeViewModel.kt:78)
        at com.codingblocks.cbonlineapp.viewmodels.HomeViewModel$fetchRecommendedCourses$1.invoke(HomeViewModel.kt:19)
        at com.codingblocks.cbonlineapp.extensions.RetrofitHelperKt$retrofitCallback$1.onResponse(RetrofitHelper.kt:10)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6784)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)

**Smartphone Info:**
|Device         |[Lenovo k8 note]|
|Android Version|[ Oreo 8.0]     |

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

**Comment by aggarwalpulkit596** [comment]
@adityastic can you confirm it?

**Comment by adityastic** [comment]
@aggarwalpulkit596 yes sir, it crashes

**Comment by adityastic** [comment]
@aggarwalpulkit596 this seems to have been fixed. It can be closed
