### ISSUE TITLE
Handle SocketTimeoutException 

### ISSUE THREAD

**Issue by aggarwalpulkit596** [coding-blocks/CBOnlineApp#284]
Fatal Exception: java.net.SocketTimeoutException: timeout
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
       at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
       at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at com.codingblocks.onlineapi.Clients$ClientInterceptor$1.intercept(Clients.java:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

Network Calls should be handled correctly when there is no response from server or server is taking to long to respond

**Comment by raystatic** [comment]
i will take this one

**Comment by adityastic** [comment]
I would like to work on it, please provide more description on it

**Comment by aggarwalpulkit596** [comment]
@raystatic @adityastic before making a PR tell me how you will be implementing it and then I'll assign it to one of you

**Comment by adityastic** [comment]
@aggarwalpulkit596 I will add ConnectionPool when creating Client. This ConnectionPool will not keep failed sockets with a default read timeout and which will automatically retry on connectionfailure

**Comment by raystatic** [comment]
@aggarwalpulkit596 I will handle it by catching the timeout exception and prevent the app from getting crashed

**Comment by adityastic** [comment]
@aggarwalpulkit596 any updates on this?. I will start working on data binding from today though

**Comment by aggarwalpulkit596** [comment]
> @aggarwalpulkit596 any updates on this?. I will start working on data binding from today though

Running busy lately will let you know in a day or two

**Comment by aggarwalpulkit596** [comment]
@adityastic Go Ahead with your implementation

**Comment by adityastic** [comment]
@aggarwalpulkit596 on it
