### ISSUE TITLE
Crash -- When Opens a PDF from Curriculum and returns back to app. It crashes

### ISSUE THREAD

**Issue by prathamk22** [coding-blocks/CBOnlineApp#708]
**Describe the bug**
1. Go to My Courses
2. Select the course and head to Curriculum section
3. Open any pdf which shows downloaded in notification pannel
4. Return back to CBOnline App and boom it crashes

**Logs**
020-05-15 08:45:48.968 29874-29874/com.codingblocks.cbonlineapp.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingblocks.cbonlineapp.debug, PID: 29874
    java.lang.RuntimeException: Unable to destroy activity {com.codingblocks.cbonlineapp.debug/com.codingblocks.cbonlineapp.PdfActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class <unknown>
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4652)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.codingblocks.cbonlineapp.util.extensions.ViewExtensionsKt.getLoadingDialog(ViewExtensions.kt:265)
        at com.codingblocks.cbonlineapp.baseclasses.BaseCBActivity$loadingDialog$2.invoke(BaseCBActivity.kt:22)
        at com.codingblocks.cbonlineapp.baseclasses.BaseCBActivity$loadingDialog$2.invoke(BaseCBActivity.kt:18)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.codingblocks.cbonlineapp.baseclasses.BaseCBActivity.getLoadingDialog(Unknown Source:2)
        at com.codingblocks.cbonlineapp.baseclasses.BaseCBActivity.onDestroy(BaseCBActivity.kt:33)
        at com.codingblocks.cbonlineapp.PdfActivity.onDestroy(PdfActivity.kt:133)
        at android.app.Activity.performDestroy(Activity.java:7595)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1257)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4652)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
        at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
        at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:122)
2020-05-15 08:45:48.969 29874-29874/com.codingblocks.cbonlineapp.debug E/AndroidRuntime:     at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:112)
        	... 29 more

**Smartphone Info:**

Device          Samsung J7 Prime  

Android Version   Oreo 8.1    

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by prathamk22** [comment]
@aggarwalpulkit596 please review and let me know. I want to work on this issue.

**Comment by aggarwalpulkit596** [comment]
Actually i fixed in the latest push can you rebase your local fork and check if it's still persist
